package routers

import (
	"frbktg/backend_go/config"
	_ "frbktg/backend_go/docs" // docs is generated by Swag CLI
	"frbktg/backend_go/repositories"
	"frbktg/backend_go/services"
	"log/slog"

	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
	"gorm.io/gorm"
)

type Router struct {
	db           *gorm.DB
	appSettings  config.Settings
	logger       *slog.Logger
	tokenService services.TokenService
	userRepo     repositories.UserRepository
}

func NewRouter(db *gorm.DB, appSettings config.Settings, logger *slog.Logger, tokenService services.TokenService, userRepo repositories.UserRepository) *Router {
	return &Router{db: db, appSettings: appSettings, logger: logger, tokenService: tokenService, userRepo: userRepo}
}

func (r *Router) SwaggerRouter(router *gin.Engine) {
	router.GET("/api/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))
}
