// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminUser = { id: number, login: string, telegram_id: number | null, created_at: string, updated_at: string, deleted_at: string | null, created_by: number, };

export type AdminUserWithRoles = { id: number, login: string, telegram_id: number | null, created_at: string, updated_at: string, deleted_at: string | null, created_by: number, roles: Array<RoleSummary>, };

export type NewAdminUser = { login: string, password: string, roles: Array<number>, };

export type NewAdminUserResponse = { id: number, login: string, telegram_id: number | null, created_at: string, updated_at: string, deleted_at: string | null, created_by: number, two_fa_secret: string, two_fa_qr_code: string, };

export type RoleSummary = { id: number, name: string, };

export type UpdateAdminUser = { login?: string, password?: string, telegram_id?: number, roles?: Array<number>, };
