// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminUser = { id: bigint, login: string, telegram_id: bigint | null, created_at: string, updated_at: string, deleted_at: string | null, created_by: bigint, };

export type AdminUserWithRoles = { id: bigint, login: string, telegram_id: bigint | null, created_at: string, updated_at: string, deleted_at: string | null, created_by: bigint, roles: Array<RoleSummary>, };

export type NewAdminUser = { login: string, password: string, roles: Array<bigint>, };

export type NewAdminUserResponse = { id: bigint, login: string, telegram_id: bigint | null, created_at: string, updated_at: string, deleted_at: string | null, created_by: bigint, two_fa_secret: string, two_fa_qr_code: string, };

export type RoleSummary = { id: bigint, name: string, };

export type UpdateAdminUser = { login?: string, password?: string, telegram_id?: bigint, roles?: Array<bigint>, };
