// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type AuditAction = "user_login" | "user_logout" | "user_create" | "user_update" | "user_delete" | "role_grant" | "role_revoke" | "permission_grant" | "permission_revoke" | "product_create" | "product_update" | "product_delete" | "product_hide" | "stock_movement_create" | "balance_deposit" | "balance_withdrawal" | "referral_payout" | "invoice_create" | "invoice_pay" | "invoice_expire" | "category_create" | "category_update" | "category_delete" | "customer_create" | "customer_update" | "customer_delete" | "bot_create" | "bot_update" | "bot_delete" | "image_create" | "image_update" | "image_delete" | "system_settings_update" | "broadcast_create" | "broadcast_update";

export type AuditLog = { id: bigint, admin_user_id: bigint | null, admin_user_login: string | null, customer_id: bigint | null, action: AuditAction, status: AuditStatus, target_table: string, target_id: string, old_values: JsonValue | null, new_values: JsonValue | null, ip_address: string | null, user_agent: string | null, request_id: string | null, error_message: string | null, created_at: string, };

export type AuditStatus = "success" | "failed" | "denied";
