// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LoginStep1 = { login: string, password: string, };

export type LoginStep1Response = { temp_token: string, };

export type LoginStep2 = { temp_token: string, code: string, };

export type LoginStep2Response = { token: string, };

export type NewRole = { name: string, description?: string, };

export type PermissionEffect = "allow" | "deny";

export type PermissionResponse = { id: bigint, name: string, group: string, description: string | null, };

export type Role = { id: bigint, name: string, description: string | null, created_at: string, updated_at: string, created_by: bigint, };

export type UpdateRole = { name?: string, description?: string | null, };

export type UpdateRolePermissions = { added: Array<bigint>, removed: Array<bigint>, };

export type UpdateUserPermission = { id: bigint, effect: PermissionEffect | null, };

export type UpdateUserPermissions = { removed: Array<bigint>, upserted: Array<UpsertUserPermission>, };

export type UpsertUserPermission = { id: bigint, effect: PermissionEffect, };

export type UserPermission = { id: bigint, effect: PermissionEffect, };
