// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BalanceRequest = { id: number, request_type: StoreBalanceRequestType, wallet_address: string, amount_usdt: number, fx_rate_rub_to_usdt: number, amount_rub: number, status: StoreBalanceRequestStatus, operator_tg_user_id: number | null, operator_comment: string | null, operator_action_at: string | null, telegram_message_id: number | null, telegram_chat_id: number | null, debit_transaction_id: number | null, credit_transaction_id: number | null, refund_transaction_id: number | null, created_at: string, updated_at: string, };

export type CreateBalanceRequest = { request_type: StoreBalanceRequestType, wallet_address: string, amount_rub: number, };

export type StoreBalanceRequestStatus = "pending_operator" | "completed" | "rejected" | "canceled";

export type StoreBalanceRequestType = "withdrawal" | "deposit";
