// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type Broadcast = { id: bigint, status: BroadcastStatus, content_text: string | null, content_image_id: string | null, filters: JsonValue | null, statistics: JsonValue | null, created_by: bigint, scheduled_for: string | null, started_at: string | null, finished_at: string | null, created_at: string, updated_at: string, };

export type BroadcastStatus = "pending" | "scheduled" | "in_progress" | "completed" | "failed";

export type NewBroadcast = { content_text?: string, content_image_id?: string, filters?: any, scheduled_for?: string, };

export type UpdateBroadcast = { content_text?: string | null, content_image_id?: string | null, filters?: any, scheduled_for?: string | null, };
