// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Customer = { id: number, telegram_id: number, balance: number, is_blocked: boolean, bot_is_blocked_by_user: boolean, has_passed_captcha: boolean, registered_with_bot: number, last_seen_with_bot: number, last_seen_at: string, created_at: string, updated_at: string, };

export type UpdateCustomer = { is_blocked?: boolean, };
