// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type ApiError = { code: ErrorCode, message: string, details: JsonValue | null, };

export type ErrorCode = "BAD_REQUEST" | "UNAUTHORIZED" | "VALIDATION_FAILED" | "INVALID_CREDENTIALS" | "INVALID_AUTH_HEADER" | "MISSING_AUTH_HEADER" | "FORBIDDEN" | "NOT_FOUND" | "CONFLICT" | "INTERNAL";
