// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ImageResponse = { id: string, context: string, created_at: string, created_by: number, };
