// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PaymentSystem } from "./payment";

export type InvoiceStatus = "pending" | "processing" | "awaiting_receipt" | "receipt_submitted" | "disputed" | "completed" | "failed" | "expired" | "cancelled" | "refunded";

export type PaymentInvoice = { id: number, customer_id: number, original_amount: number, amount: number, status: InvoiceStatus, created_at: string, updated_at: string, expires_at: string, gateway: PaymentSystem, gateway_invoice_id: string, };
