// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type InvoiceStatus = "pending" | "processing" | "awaiting_receipt" | "receipt_submitted" | "disputed" | "completed" | "failed" | "expired" | "cancelled" | "refunded";
