// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Order = { id: number, customer_id: number, amount: number, currency: string, status: OrderStatus, bot_id: number, created_at: string, updated_at: string, paid_at: string | null, fulfilled_at: string | null, cancelled_at: string | null, };

export type OrderStatus = "created" | "paid" | "fulfilled" | "cancelled" | "refunded";
