// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type NewProduct = { name: string, base_price: number, category_id: number, image_id?: string, type: ProductType, subscription_period_days?: number, details?: JsonValue, fulfillment_text?: string, fulfillment_image_id?: string, initial_stock?: number, };

export type Product = { id: number, name: string, base_price: number, price: number, stock: number, category_id: number | null, image_id: string | null, type: ProductType, subscription_period_days: number, details: ProductDetails | null, deleted_at: string | null, fulfillment_text: string | null, fulfillment_image_id: string | null, provider_name: string, external_id: string | null, created_at: string, updated_at: string, created_by: number, };

export type ProductDetails = { "cont_ms": { host: string, port: number, } };

export type ProductType = "item" | "subscription";

export type UpdateProduct = { name?: string, base_price?: number, category_id?: number, image_id?: string | null, type?: ProductType, subscription_period_days?: number, details?: JsonValue | null, fulfillment_text?: string | null, fulfillment_image_id?: string | null, external_id?: string | null, stock?: number, };

export type UploadProductsResponse = { created: number, failed: number, skipped: number, errors: Array<string>, };
