// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StockMovement = { id: bigint, order_id: bigint | null, product_id: bigint, product_name: string, type: StockMovementType, quantity: bigint, created_at: string, created_by: bigint, description: string | null, };

export type StockMovementType = "initial" | "restock" | "sale" | "return" | "adjustment";
