// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StockMovement = { id: number, order_id: number | null, product_id: number, product_name: string, type: StockMovementType, quantity: number, created_at: string, created_by: number, description: string | null, };

export type StockMovementType = "initial" | "restock" | "sale" | "return" | "adjustment";
