package gateways

import (
	"net/http"
)

// InvoiceCreationRequest contains the data needed to create an invoice.
type InvoiceCreationRequest struct {
	Amount    float64 `json:"amount"`
	UserID    uint    `json:"user_id"`
	OrderID   string  `json:"order_id"` // A unique ID generated by our system for this transaction
}

// Invoice represents the response from a payment gateway after creating an invoice.
type Invoice struct {
	GatewayInvoiceID string `json:"gateway_invoice_id"` // The ID of the invoice in the gateway's system
	PayURL           string `json:"pay_url"`            // The URL the user should be redirected to for payment
}

// WebhookResult contains the data parsed from a webhook notification.
type WebhookResult struct {
	GatewayInvoiceID string
	OrderID          string
	Status           string // e.g., "completed", "failed"
	Amount           float64
}

// PaymentGateway defines the interface for all payment providers.
type PaymentGateway interface {
	// GetName returns the unique name of the gateway (e.g., "mock_provider").
	GetName() string

	// GetDisplayName returns a user-friendly name for the gateway.
	GetDisplayName() string

	// CreateInvoice creates a payment invoice in the external system.
	CreateInvoice(req *InvoiceCreationRequest) (*Invoice, error)

	// HandleWebhook parses an incoming webhook, verifies it, and returns a structured result.
	// It is responsible for validating the integrity of the webhook (e.g., checking signatures).
	HandleWebhook(r *http.Request) (*WebhookResult, error)
}
