import { AuditAction } from "@/types";

export const AUDIT_ACTIONS_TRANSLATIONS = {
  user_login: "Вход в систему",
  user_logout: "Выход из системы",
  user_create: "Создание пользователя",
  user_update: "Обновление пользователя",
  user_delete: "Удаление пользователя",
  role_grant: "Назначение роли",
  role_revoke: "Отзыв роли",
  permission_grant: "Предоставление разрешения",
  permission_revoke: "Отзыв разрешения",
  product_create: "Создание товара",
  product_update: "Обновление товара",
  product_delete: "Удаление товара",
  product_hide: "Скрытие товара",
  stock_movement_create: "Создание движения на складе",
  balance_deposit: "Пополнение баланса",
  balance_withdrawal: "Списание средств с баланса",
  referral_payout: "Выплата по реферальной программе",
  invoice_create: "Создание счёта",
  invoice_pay: "Оплата счёта",
  invoice_expire: "Истечение срока действия счёта",
  category_create: "Создание категории",
  category_update: "Обновление категории",
  category_delete: "Удаление категории",
  customer_create: "Создание клиента",
  customer_update: "Обновление клиента",
  customer_delete: "Удаление клиента",
  bot_create: "Создание бота",
  bot_update: "Обновление бота",
  bot_delete: "Удаление бота",
  image_create: "Загрузка изображения",
  image_update: "Обновление изображения",
  image_delete: "Удаление изображения",
  system_settings_update: "Обновление системных настроек",
  broadcast_create: "Создание рассылки",
  broadcast_update: "Обновление рассылки",
} as const satisfies Record<AuditAction, string>;
