export const ENDPOINTS = {
  USERS_ME: "me",
  ME_PERMISSIONS: "me/permissions",
  ADMIN_SETTINGS: "admin/settings",
  ADMIN_PAYMENT_PROVIDERS: "admin/payment-providers",
  REFERRALS: "referrals",
  REFERRAL_BOTS_ADMIN: "referrals/admin-list",
  ADMIN_REFERRAL_BOTS: "admin/referral-bots",
  CATEGORIES: "categories",
  PRODUCTS: "products",
  TRANSACTIONS: "transactions",
  STOCK_MOVEMENTS: "stock/movements",
  DASHBOARD_STATS: "dashboard/stats",
  DASHBOARD_TIME_SERIES: "dashboard/time-series",
  DASHBOARD_TOP_PRODUCTS: "dashboard/top-products",
  DASHBOARD_SALES_BY_CATEGORY: "dashboard/sales-by-category",
  BOT_USERS: "admin/bot-users",
  BROADCAST_USERS: "admin/broadcasts/users",
  BROADCAST_SEND: "admin/broadcasts/send",
  TOGGLE_BLOCK: "admin/bot-users/:id/toggle-block",
  IMAGES: "admin/images",
  IMAGE_FOLDERS: "admin/image-folders",
  REFERRAL_PERCENTAGE: "referrals/:id/percentage",
  ROLES: "admin/roles",
  PERMISSIONS: "admin/permissions",
  ROLE_PERMISSIONS: "admin/roles/:id/permissions",
  USER_PERMISSIONS: "admin/users/:id/permissions",
  USERS: "admin/users",
  USER_ROLES: "admin/users/:id/roles",
  AUDIT_LOGS: "admin/audit-logs",
  PRODUCTS_UPLOAD_CSV: "products/upload",
  STORE_BALANCE: "admin/store-balance",
};

export const ENDPOINT_UPDATE_PUT_EXCEPTIONS = new Set<string>([
  ENDPOINTS.ADMIN_SETTINGS,
  ENDPOINTS.REFERRALS,
  ENDPOINTS.SET_BOT_PRIMARY,
  ENDPOINTS.CATEGORIES,
  ENDPOINTS.REFERRAL_PERCENTAGE,
  ENDPOINTS.USER_ROLES,
  ENDPOINTS.ROLES,
]);
