export const ENDPOINTS = {
  USERS_ME: "me",
  ME_PERMISSIONS: "me/permissions",
  PRICING_SETTINGS: "settings/pricing",
  BOT_SETTINGS: "settings/bot",
  ADMIN_PAYMENT_PROVIDERS: "admin/payment-providers",
  REFERRALS: "referrals",
  REFERRAL_BOTS_ADMIN: "referrals/admin-list",
  BOTS: "bots",
  CATEGORIES: "categories",
  PRODUCTS: "products",
  TRANSACTIONS: "transactions",
  STOCK_MOVEMENTS: "stock-movements",
  DASHBOARD_STATS: "dashboard/stats",
  DASHBOARD_TIME_SERIES: "dashboard/time-series",
  DASHBOARD_TOP_PRODUCTS: "dashboard/top-products",
  DASHBOARD_SALES_BY_CATEGORY: "dashboard/sales-by-category",
  CUSTOMERS: "customers",
  BROADCAST: "broadcasts",
  IMAGES: "images",
  IMAGE_FOLDERS: "admin/image-folders",
  ROLES: "roles",
  PERMISSIONS: "permissions",
  ROLE_PERMISSIONS: "roles/:id/permissions",
  USER_PERMISSIONS: "admin-users/:id/permissions",
  USERS: "admin-users",
  USER_ROLES: "admin-users/:id/roles",
  AUDIT_LOGS: "audit-logs",
  PRODUCTS_UPLOAD_CSV: "products/upload",
  STORE_BALANCE: "store-balance",
  ORDERS: "orders",
};

export const ENDPOINT_UPDATE_PUT_EXCEPTIONS = new Set<string>([
  ENDPOINTS.USER_ROLES,
]);
